services:
  web:
    build:
      context: ./reference/netology_pd_diplom
      dockerfile: ../../docker/Dockerfile
    container_name: netology_web
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./reference/netology_pd_diplom:/app
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: netology_pd_diplom_project.settings
      PYTHONPATH: /app

  celery:
    build:
      context: ./reference/netology_pd_diplom
      dockerfile: ../../docker/Dockerfile
    container_name: netology_celery
    command: celery -A netology_pd_diplom_project worker --loglevel=info
    env_file:
      - .env
    volumes:
      - ./reference/netology_pd_diplom:/app
    working_dir: /app
    depends_on:
      - redis
      - web
    environment:
      DJANGO_SETTINGS_MODULE: netology_pd_diplom_project.settings
      PYTHONPATH: /app

  redis:
    image: redis:7
    container_name: netology_redis
    ports:
      - "6379:6379"
